### ISSUE TITLE
The wildchild constraint seem to be ignored

### ISSUE THREAD

**Issue by gajuro** [firebase/blaze_compiler#20]
Given the next yaml file:

``` yaml
functions:
  - isWorkspaceRole(userId, workspaceId, role): root['/rels/workspaces/users/' + workspaceId][userId]['role'] == role

schema:
  properties:
    rels:
      properties:
        workspaces:
          properties:
            users:
              $workspace_id:
                constraint: isWorkspaceRole(auth.id, $workspace_id, 'administrator') ||
                            isWorkspaceRole(auth.id, $workspace_id, 'collaborator') && next != null
                ~$user_id: {}
```

This is what gets generated with the latest three versions of blaze:

``` json
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "rels": {
      ".write":"false",
      ".read":"false",
      "workspaces": {
        ".write":"false",
        ".read":"false",
        "users": {
          ".write":"false",
          ".read":"false",
          "$workspace_id": {
            ".write":"false",
            ".read":"false",
            "$user_id": {
              ".write":"false",
              ".validate":"false",
              ".read":"false"
            }
          }
        }
      }
    }
  }
}
```

This is the output of blaze 0.0.14:

``` json
{
  "rules":{
    ".write":"true&&true&&true&&true&&false&&false",
    ".read":"false",
    "rels": {
      ".write":"true&&true&&true&&false&&false",
      ".read":"false",
      "workspaces": {
        ".write":"true&&true&&false&&false",
        ".read":"false",
        "users": {
          ".write":"true&&false&&false",
          ".read":"false",
          "$workspace_id": {
            ".write":"true&&true&&false",
            ".read":"false",
            "$user_id": {
              ".write":"true&&true&&true&&true&&(root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='administrator'||root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='collaborator'&&newData.parent().val()!=null)&&true&&false",
              ".validate":"true&&true&&true&&true&&(root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='administrator'||root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='collaborator'&&newData.parent().val()!=null)&&true&&false",
              ".read":"false"
            }
          }
        }
      }
    }
  }
}
```

Am I doing something wrong? Thanks.
