### ISSUE TITLE
Some access expressions are not translated when copied to descendants

### ISSUE THREAD

**Issue by gajuro** [firebase/blaze_compiler#21]
Given the next yaml:

``` yaml
functions:
  - isWorkspaceRole(userId, workspaceId, role): root['/rels/workspaces/users/' + workspaceId][userId]['role'] == role

schema:
  properties:
    rels:
      properties:
        workspaces:
          properties:
            users:
              $workspace_id:
                ~$user_id: {}

access:
- location: /rels/workspaces/users/$workspace_id
  write:    isWorkspaceRole(auth.id, $workspace_id, 'administrator') ||
            isWorkspaceRole(auth.id, $workspace_id, 'collaborator') && next != null
```

The following code is generated:

``` json
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "rels": {
      ".write":"false",
      ".read":"false",
      "workspaces": {
        ".write":"false",
        ".read":"false",
        "users": {
          ".write":"false",
          ".read":"false",
          "$workspace_id": {
            ".write":"(((root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='administrator'||root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='collaborator'&&newData.val()!=null)))",
            ".read":"false",
            "$user_id": {
              ".write":"(((root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='administrator'||root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='collaborator'&&newData.val()!=null)))",
              ".validate":"(((root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='administrator'||root.child('/rels/workspaces/users/'+$workspace_id).child(auth.id).child('role').val()=='collaborator'&&newData.val()!=null)))",
              ".read":"false"
            }
          }
        }
      }
    }
  }
}
```

While `newData.val()!=null` makes sense for the parent, it doesn't for the child. Shouldn't it be translated to `newData.parent().val()!=null` ? Thanks.
