### ISSUE TITLE
Acces rules of wilderchild are ignored

### ISSUE THREAD

**Issue by gajuro** [firebase/blaze_compiler#22]
Given:

``` yaml
functions:
  - isWorkspaceRole(userId, workspaceId, role): root['/rels/workspaces/users/'][workspaceId][userId]['role'] == role

schema:
  properties:
    rels:
      properties:
        workspaces:
          properties:
            users:
              $workspace_id:
                ~$user_id: {}

access:
  - location: /rels/workspaces/users/$workspace_id/$user_id
    write:    isWorkspaceRole(auth.id, $workspace_id, 'administrator')
```

Results in:

``` json
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "rels": {
      ".write":"false",
      ".read":"false",
      "workspaces": {
        ".write":"false",
        ".read":"false",
        "users": {
          ".write":"false",
          ".read":"false",
          "$workspace_id": {
            ".write":"false",
            ".read":"false",
            "$user_id": {
              ".write":"false",
              ".validate":"false",
              ".read":"false"
            }
          }
        }
      }
    }
  }
}
```

However the access rule is considered if I turn `~$user` into `$user`.
