### ISSUE TITLE
Access rules coming from functions are not translated when copied to descendants

### ISSUE THREAD

**Issue by gajuro** [firebase/blaze_compiler#23]
``` yaml
functions:
  - isDeleted()                               : prev.exists() && !next.exists()

schema:
  properties:
    rels:
      properties:
        workspaces:
          properties:
            users:
              $workspace_id:
                ~$user_id: {}

access:
  - location: /rels/workspaces/users/$workspace_id
    write:    isDeleted()
```

generates

``` json
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "rels": {
      ".write":"false",
      ".read":"false",
      "workspaces": {
        ".write":"false",
        ".read":"false",
        "users": {
          ".write":"false",
          ".read":"false",
          "$workspace_id": {
            ".write":"((data.exists()&&!newData.exists()))",
            ".read":"false",
            "$user_id": {
              ".write":"((data.exists()&&!newData.exists()))",
              ".validate":"((data.exists()&&!newData.exists()))",
              ".read":"false"
            }
          }
        }
      }
    }
  }
}
```
