### ISSUE TITLE
Producing global read/write rules

### ISSUE THREAD

**Issue by erikcw** [firebase/blaze_compiler#29]
Just getting started with a simple rule set:

```yaml
functions:
  - isLoggedIn(): auth.id !== null

schema: {}

access:
  - location: dashboard/$slug/
    read:  isLoggedIn() && prev.user === auth.uid
    write: false
```

Produces:

```json

{
  "rules":{
    ".write":"false",
    ".read":"false"
  }
}

```

What happened to the write rules?

This is what I'm trying to recreate:

```json
{
    "rules": {
        "dashboard": {
          "$slug": {
            ".read": "data.child('user').val() === auth.uid",
            ".write": false
          }
        }
    }
}
```
