### ISSUE TITLE
Examples and nonexamples don't seem to honor constraints

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#30]
I'm trying to write examples that would test against a defined constraint, and the constraints don't seem to be taken into account when compiling. A simplified example:

``` yaml
email:
  type: string
  constraint: next.val().matches(/^[^@]+@.+\..+$/i) # rudimentary email address checking
examples:
  - "niko@tidyplan.com"
nonexamples: # for all of these nonexamples compiler says they pass when they should fail
  - "niko"
  - "@tidyplan.com"
  - "niko@com"
```

The regex matching works when I push it to Firebase, so the problem is definitely with the compiler. 

Or maybe this is by design, and the compiler is not supposed to validate against the constraints?
