### ISSUE TITLE
Unexpected function scope

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#31]
In my rules yaml I have the following code:

``` yaml
functions:
  - within24hours(): next > (now - 1000*60*60*24)

items:
  type: object
  $itemId:
    type: object
    properties:
      title:
        type: string
      itemDate:
        type: number
        constraint: within24hours()
```

I expect this would write rules along the lines of:

``` json
newData.child('title').isString()) && newData.child('itemDate').val() > now-1000*60*60*24
```

Instead I get this (which obviously doesn't work):

``` json
newData.child('title').isString()) && newData.val() > now-1000*60*60*24
```

Is this intended behaviour?
