### ISSUE TITLE
Unknown variable error when using functions

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#32]
I tried a function with an argument:

``` yaml
functions:
  - within24hours(nxt): nxt > (now - 1000*60*60*24)
```

...and elsewhere I'm passing the value to the argument:

``` yaml
itemDate:
  type: number
  constraint: within24hours(next.val()) # not sure if .val() is needed...
```

The compiler outputs the following rules that cause an error when saving the rules in Firebase dashboard:

``` json
newData.isNumber() && nxt>now-1000*60*60*24
```
