### ISSUE TITLE
Setting a minimum for a number effectively makes the property required?

### ISSUE THREAD

**Issue by nnyman** [firebase/blaze_compiler#33]
If I have the following yaml rules:

``` yaml
items:
  type: object
  $itemId:
    type: object
    required: [title]
    properties:
      title: {type: string}
      timestamp:
        type: number
        minimum: 0
```

...and I pass the following JSON in the Firebase simulator to `/items/item1`:

``` JSON
{ "title": "First item" }
```

...I get this error:

```
Type error: >= only operates on numbers and strings.
```

Looking at the compiled rules, I'm assuming the system is comparing null to the minimum value of 0.

I haven't figured a good way around this. A couple of workarounds:
1. Always pass `timestamp:0` in the JSON data, or
2. Replace the `minimum` with `constraint: (!next.exists()) || (next.isNumber() && next > 0)`
3. Update the documentation to explain that setting a minimum makes the property required. :smiley:
