### ISSUE TITLE
Confusing error for `-` in wildchild name.

### ISSUE THREAD

**Issue by jyasskin** [firebase/blaze_compiler#40]
`rules.yaml`:
```yaml
schema:
  type: object
  additionalProperties: false
  $foo-bar:
    type: string
    constraint: $foo-bar.matches(/regex/)
```

`blaze rules.yaml` yields:
> Error: Bug: 3 Unexpected situation in type system undefined undefined
>    at falafel_visitor (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/src/expression.ts:342:167)
>    at walk (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:60:9)
>    at /home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:57:17
>    at Array.forEach (native)
>    at forEach (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:8:31)
>    at walk (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:44:9)
>    at /home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:57:17
>    at Array.forEach (native)
>    at forEach (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:8:31)
>    at walk (/home/jyasskin/opt/nodejs/lib/node_modules/blaze_compiler/node_modules/falafel/index.js:44:9)
