### ISSUE TITLE
Function at constraint different than function body at constraint

### ISSUE THREAD

**Issue by CurtisHumphrey** [firebase/blaze_compiler#43]
I have two cases:
```yaml
functions:
  - createOrUpdate(): next.exists() && prev.exists() || !prev.exists()

schema:
  properties:
    menus:
      $user_id:
        $menu_id:
          properties:
            days:
              constraint: next.exists() && prev.exists() || !prev.exists()

access:
  - location: 'menu/$user_id/$menu_id'
  - write: true
```
Which generates:
```json
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "menus": {
      ".write":"((false))",
      ".read":"(auth!==null)",
      "$user_id": {
        ".write":"((false))",
        ".read":"(auth!==null)",
        "$menu_id": {
          ".write":"((((newData.child('days').exists()&&data.child('days').exists()||!data.child('days').exists()))))",
          ".read":"((auth!==null))",
          "days": {
            ".write":"(((newData.exists()&&data.exists()||!data.exists())))",
            ".read":"((auth!==null))"
          }
        }
      }
    }
}
```

However if I replace the constraint with the function I get a different output.  I don't understand, why?

```yaml
functions:
  - createOrUpdate(): next.exists() && prev.exists() || !prev.exists()
schema:
  properties:
    dev: {}
    lists:
      type: object
      $list_name:
        type: object
        $list_item: {}

    menus:
      $user_id:
        $menu_id:
          properties:
            days:
              constraint: createOrUpdate()
```
```json
{
  "rules":{
    ".write":"false",
    ".read":"false",
   "menus": {
      ".write":"((false))",
      ".read":"(auth!==null)",
      "$user_id": {
        ".write":"((false))",
        ".read":"(auth!==null)",
        "$menu_id": {
          ".write":"((((newData.exists()&&data.exists()||!data.exists()))))",
          ".read":"((auth!==null))",
          "days": {
            ".write":"(((newData.exists()&&data.exists()||!data.exists())))",
            ".read":"((auth!==null))"
          }
        }
      }
    }
}
```
