### ISSUE TITLE
Add warnings for ignored access rules that have no corresponding schema or automatically generate them

### ISSUE THREAD

**Issue by OzzieOrca** [firebase/blaze_compiler#49]
I spent several hours trying to figure out why this:

```
functions:
  - hasAuth(): auth !== null
  - isAdmin(): hasAuth() && root.users[auth.uid].role === 'admin'
  - authMatchesPath(userUid): hasAuth() && auth.uid === userUid

schema:
  type: object
  properties:
    menu:
      type: object
    pages:
      type: object
    users:
      type: object
      $useruid:
        type: object
        required: [name, email]
        properties:
          name:
            type: string
          email:
            type: string
          profilePicture:
            type: string
          role:
            type: string
            enum: [admin, user]
        additionalProperties: false

        examples:
          - {name: "My Name", email: "myemail@example.com"}
          - {name: "My Name", email: "myemail@example.com", role: "admin"}
          - {name: "My Name", email: "myemail@example.com", role: "user"}
          - {name: "My Name", email: "myemail@example.com", profilePicture: "http://url.com"}
          - {name: "My Name", email: "myemail@example.com", profilePicture: "http://url.com", role: "admin"}
          - {name: "My Name", email: "myemail@example.com", profilePicture: "http://url.com", role: "user"}
        nonexamples:
          - {new:   "value"}
          - {name:  "My Name"}
          - {email: "myemail@example.com"}
          - {name:  "My Name", email: "myemail@example.com", role: "somethingElse"}

access:
  - location: "/menu/"
    read: true
    write: isAdmin()
  - location: "/pages/"
    read: true
    write: isAdmin()
  - location: "/users/"
    read: isAdmin()
  - location: "/users/$user_uid/"
    read: authMatchesPath($user_uid) || isAdmin()
    write: authMatchesPath($user_uid)
  - location: "/users/$user_uid/role/"
    write: isAdmin()
```
generated this

```
{
  "rules":{
    ".write":"false",
    ".read":"false",
    "menu": {
      ".write":"((((!newData.exists()||newData.hasChildren())&&auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin')))",
      ".read":"true"
    },
    "pages": {
      ".write":"((((!newData.exists()||newData.hasChildren())&&auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin')))",
      ".read":"true"
    },
    "users": {
      ".write":"((false))",
      ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))",
      "$useruid": {
        ".write":"(false)",
        ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))",
        "name": {
          ".write":"(false)",
          ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))"
        },
        "email": {
          ".write":"(false)",
          ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))"
        },
        "profilePicture": {
          ".write":"(false)",
          ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))"
        },
        "role": {
          ".write":"(false)",
          ".read":"((auth!==null&&root.child('users').child(auth.uid).child('role').val()==='admin'))"
        },
        "$other":{".validate":"false"}
      }
    }
  }
}
```
where the rules under `location: "/users/$user_uid/"` and `location: "/users/$user_uid/role/"`did absolutely nothing.

Then I discovered that in `schema` I had `$useruid` and in `access` I had `$user_uid`. I made them the same named variable and it worked. I REALLY would have appreciated some documentation or error messages explaining that the all the paths in `access` have to map to something in `schema`. I think this might be the same issue as https://github.com/firebase/blaze_compiler/issues/29.

I think warnings should be added for any `access` rule that is ignored because there is no matching `schema` for it. I had the same problem with defining `/menu/` and `/pages/` rules and discovered I needed to specify a `schema` for them.

Maybe it is good to force a strict schema but for development purposes I think it would be nice to be able to specify `access` rules without having to create a `schema` that matches every single location in order to test security rules. Without that feature, it just drops rules with no explanation.
