### ISSUE TITLE
Add duplicate examples warning

### ISSUE THREAD

**Issue by OzzieOrca** [firebase/blaze_compiler#51]
This is not a big deal and is entirely my fault but I had a list of several examples and accidently duplicated 2 of the examples.
```
schema:
  type: object
  properties:
    users:
      type: object
      $user_uid:
        type: object
        required: [name, email]
        properties:
          name:
            type: string
          email:
            type: string

        examples:
          - {name: "My Name", email: "myemail@example.com"}
          - {name: "My Name", email: "myemail@example.com"}
```
I got this lovely error message which gave me no indication that the examples were the issue:
```
error line 8:18
[ 'name', 'email' ]
cannot validate blaze file with blaze schema
data was on path: /schema/properties/users/$user_uid/required
the schema constraint was defined at 
Unknown property (not in schema)
run with -v option for fuller error messages
```
I finally noticed the duplicate example and figure that might be the issue and sure enough that fixed it. A better error message would be nice. This could be part of the YAML parser itself and be harder to add.
