### ISSUE TITLE
Nested functions to not properly wrap conditions

### ISSUE THREAD

**Issue by tyrsius** [firebase/blaze_compiler#68]
I have some nested functions that I have wrapped in parens at multiple levels, yet the output strips all of them, producing a flat boolean series.

```
functions:
  - isUser(uid): (auth.uid !== null && auth.uid === uid)
  - hasRole(roleName): (root.users[auth.uid].role === roleName && isVerified())
  - isBoardMember(): (hasRole('Board Member'))
  - isAdmin(): (hasRole('Admin'))
  - isManager(): ((isAdmin()) || (isBoardMember()))
  - isVerified(): (root.users[auth.uid].role !== 'Unverified' && root.users[auth.uid].role.exists())

schema:
  type: object
  properties:
    users:
      type: object
      $userId:
        type: object
        constraint: ((isManager()) || (isUser($userId)))
        properties:
          role:
            type: string
            constraint: ((isManager()) && next !== 'Admin')
```

The offending output. Notice how all the conditions are equal, producing incomprehensible AND's and OR's, instead of a proper tree.
```
"$userId": {
        ".write":"(
          (
            (
              (root.child('users').child(auth.uid).child('role').val()==='Admin'
                &&root.child('users').child(auth.uid).child('role').val()!=='Unverified'
              &&root.child('users').child(auth.uid).child('role').exists()
              ||root.child('users').child(auth.uid).child('role').val()==='Board Member'
              &&root.child('users').child(auth.uid).child('role').val()!=='Unverified'
              &&root.child('users').child(auth.uid).child('role').exists()
              ||auth.$userId!==null
              &&auth.$userId===$userId)
```
