### ISSUE TITLE
Incorrect compilation for children

### ISSUE THREAD

**Issue by hijonathan** [firebase/blaze_compiler#8]
I continually see `true&&false&&(rule_thats_actually_important)` getting generated, often incorrectly. If I understand Firebase correctly, `true&&false` will always be false regardless of what follows. Here's an example config:

``` yaml
schema:
  type: object
  properties:
    users:
      type: object
      $userId:
        type: object
        properties:
          foos:
            type: object
            $fooId: {type: object}

access:
  # No read or write by default.
  - location: /
    read: false
    write: false

  # Allow owner to write.
  - location: users/$userId/
    write: true
  - location: users/$userId/foos/
    write: true
```

Which generates the following:

``` json
{
  "rules":{
    ".write":"true&&true&&false&&(false||false)",
    ".read":"false||false",
    "users": {
      ".write":"true&&false&&(false||false)",
      ".read":"false||false",
      "$userId": {
        ".write":"true&&true&&false&&(false||false||true)",
        ".read":"false||false||false",
        "foos": {
          ".write":"true&&false&&(false||false||true||true)",
          ".read":"false||false||false||false",
          "$fooId": {
            ".write":"true&&(!newData.parent().parent().parent().parent().exists()||!(newData.parent().parent().parent().parent().isString()||newData.parent().parent().parent().parent().isNumber()||newData.parent().parent().parent().parent().isBoolean()))&&(newData.parent().parent().parent().parent().val()==null||true)&&true&&(!newData.parent().parent().parent().exists()||!(newData.parent().parent().parent().isString()||newData.parent().parent().parent().isNumber()||newData.parent().parent().parent().isBoolean()))&&(newData.parent().parent().parent().val()==null||true)&&true&&(!newData.parent().parent().exists()||!(newData.parent().parent().isString()||newData.parent().parent().isNumber()||newData.parent().parent().isBoolean()))&&(newData.parent().parent().val()==null||true)&&true&&(!newData.parent().exists()||!(newData.parent().isString()||newData.parent().isNumber()||newData.parent().isBoolean()))&&(newData.parent().val()==null||true)&&true&&(!newData.exists()||!(newData.isString()||newData.isNumber()||newData.isBoolean()))&&(newData.val()==null||true)&&(false||false||true||true)",
            ".read":"false||false||false||false"
          }
        }
      }
    }
  }
}
```

That doesn't seem to jive. You'll see that we expect `/users/$userId/` to be writeable, but the value is `true&&true&&false&&(false||false||true)` which evaluates to `false`. Same is true for `/users/$userId/foos/`
